# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cefcc1442dca39d4e26938ab7671ffb8dd3023616a2d2208e57013e7b0c1c279b3f7b9c261ff0236c21b22921105a68b0746199eebf0a9d93d44c1d7c9f88240

test:
  secret_key_base: d3922b554961470616dc7d0c6da75355a3c1884811bea08c4203f07594695df75b226688b791db8ff91e94d5870ac37e4c91a77806206857c1b741319bb5c56e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
